name: MineWar
main: ca.sarkox.minewar.Main
version: 1.1
api-version: 1.18
author: Sarkox
commands:
  forcestart:
    description: force le démarage de la partie
  config:
    description: Configuration du MineWar